### ISSUE TITLE
Unhandled Exception: System.NullReferenceException:

### ISSUE THREAD

**Issue by skiz0r** [YOLOP0wn/POSTDump#1]
I have compiled the code and it got builded successful with 3 below warnings:
C:\....\POSTDump-main\POSTDump\ASR.cs(88,17,88,26): warning CS0219: The variable 'attribute' is assigned but its value is never used.
C:\....\POSTDump-main\POSTDump\Driver.cs(322,13,322,19): warning CS0162: Unreachable code detected
C:\....\POSTDump-main\POSTDump\POSTMiniDump\Data.cs(503,26,503,34): warning CS0169: The field 'Data.LDR_DATA_TABLE_ENTRY.Reserved' is never used.
Build: 1 succeeded

When I ran the POSTDump.exe --signature --driver
[+] Registry key added.
[+] Got protected process handle
[+] Driver unloaded
[+] Register key deleted
[+] Driver deleted from disk
[+] Using invalid signature
Could not find modules

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at POSTMiniDump.MiniDump.POSTDumpWriterDump(dump_context dc, Boolean InvalidSig, Boolean encrypt)
at POSTDump.Postdump.Main(String[] args)

**Comment by YOLOP0wn** [comment]
Hello, 

Does it do the same error without using driver ? Which .NET framework version are you compiling with? Is it a x86 or x64 machine? Which Windows version?

**Comment by skiz0r** [comment]
Hey,

Below are the details:
Microsoft .NET Framework 4.5.1 Multi-Targeting Pack (ENU). 
Compiled on Windows 11 x64

Does it do the same error without using driver ?
: Yes, It just only shows 
[+] Using Invalid Signature
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at POSTMiniDump.MiniDump.POSTDumpWriterDump(dump_context dc, Boolean InvalidSig, Boolean encrypt)
at POSTDump.Postdump.Main(String[] args)

**Comment by YOLOP0wn** [comment]
Windows 11 had credential guard enabled by default, that's why it doesnt work
