### ISSUE TITLE
If --driver is not specified, a process handle can never be gotten

### ISSUE THREAD

**Issue by h4rmsw4y** [YOLOP0wn/POSTDump#2]
In postdump.cs, if driver is not true, the code will be unable to get a process handle leading to a NullReferenceException later on:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at POSTMiniDump.MiniDump.write_module_list_stream(dump_context dc)
   at POSTMiniDump.MiniDump.POSTDumpWriteDump(dump_context dc, Boolean InvalidSig, Boolean encrypt)
   at POSTDump.Postdump.Main(String[] args)

Relevant snippet:
```
     if (driver && dc.hProcess == IntPtr.Zero)
            {
                Console.WriteLine("Driver technic failed, trying default method..");
                if (Elevate)
                {
                    if (!Handle.GetProcessHandle(lsassid, out procHandle, (uint)0x1000)) //PROCESS_QUERY_LIMITED_INFORMATION
                    {
                        Console.WriteLine("Open process failed!");
                        return;
                    }
```

**Comment by YOLOP0wn** [comment]
Hey dude, thanks for noticing, it should now  be fixed
